#--------------------------------------------------------------------------------------------#
# This file stores parameter info for running the large deviation algorithm w/ wrf           #
# version V0.3 by xp53, May 29 2023                                                          #
# contact me via xp53@ + cornell.edu or nus.edu.sg                                           #
#--------------------------------------------------------------------------------------------#

# path of working directory
path: '/home/climate/xp53/large_deviation2'

# a reference value for computing deficit in the score (weight) function 
# this is hard coded here since I do not expect it change frequently
ref: 7.078

# number of trajectories
N: 128

# the scaling coefficient in the score (weight) function
K: 0.05

# total number of simulation sub-intervals
T: 18

# size of the IC pool for bootsrapping 
ic_pool: 40

# total number of simulation sub-intervals
bc_pool: 40





