#!/bin/bash
#PBS -q normal
#PBS -l select=1:ncpus=4:mem=16G
#PBS -l walltime=1:00:00
#PBS -P 11002299
#PBS -e /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/ini_error.txt
#PBS -o /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/ini_output.txt
#PBS -N file_ini
module load anaconda3
cd /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/
conda activate tmp10
python mv_ic.py
