#!/bin/bash
#PBS -q normal
#PBS -l select=4:ncpus=64:mem=256G
#PBS -l walltime=24:00:00
#PBS -P 11002298
#PBS -e /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/log/slave_e1.txt
#PBS -o /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/log/slave_o1.txt
#PBS -N LDS_slave1
module load anaconda3
cd /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/
conda activate tmp10
python slave.py 1
