#!/bin/bash
#PBS -q normal
#PBS -l select=1:ncpus=128:mem=256G
#PBS -l walltime=24:00:00
#PBS -P 11002299
#PBS -e /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/log/slave_fixe.txt
#PBS -o /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/log/slave_fixo.txt
#PBS -N LDS_slavefix
module load anaconda3
cd /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/
conda activate tmp10
python slavefix.py
