#!/bin/bash
#PBS -q normal
#PBS -l select=1:ncpus=64:mem=128G
#PBS -l walltime=24:00:00
#PBS -P 11002299
#PBS -e /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/log/slave_fixe.txt
#PBS -o /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/log/slave_fixo.txt
#PBS -N LDS_slavefix

cd /scratch/users/nus/xp53/lds_multijob/large_deviation_multijob/traj/YYYY/
sed -i "32s/6/3/g" namelist.input
mpirun -np 64 ./wrf.exe
